name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Install Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath "is.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
      
    - name: Create Installer Directory
      run: mkdir -p Installer
      
    - name: Debug Directory Structure
      run: |
        Get-ChildItem -Path . -Recurse -Depth 3
        Get-ChildItem -Path bin -Recurse -Depth 3 
      
    - name: Update Inno Setup Script Path
      run: |
        Get-Content QuickConvertSetup.iss
        $absolutePath = "${{ github.workspace }}".Replace('\', '\\')
        (Get-Content QuickConvertSetup.iss) -replace 'Source: ".*?publish\\', "Source: `"$absolutePath\\bin\\Release\\net6.0-windows\\win-x64\\publish\\" | Set-Content QuickConvertSetup.iss
        Get-Content QuickConvertSetup.iss
        
    - name: Verify Files Exist
      run: |
        $publishPath = "${{ github.workspace }}\bin\Release\net6.0-windows\win-x64\publish"
        Write-Host "Checking if publish directory exists: $publishPath"
        if (Test-Path $publishPath) {
            Write-Host "Directory exists! Listing contents:"
            Get-ChildItem -Path $publishPath
        } else {
            Write-Host "Directory does not exist!"
        }
      
    - name: Build Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "QuickConvertSetup.iss"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Installer/QuickConvert_Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 